import {
  genderOptions,
  goalOptions,
  interestedInOptions,
  languageOptions,
} from "@/src/libs/options";
import type { Screen } from "./types";

export const onboardingScreens: Screen[] = [
  {
    id: "essentials",
    required: true,
    title: "Tell us the essentials to start matching.",
    fields: [
      {
        type: "text",
        place: "user",
        name: "nickname",
        label: "Nick name",
        placeholder: "Batman",
        helperText: "This will be your display name in the app.",
        errorText: "You need a nickname to use this app",
      },
      {
        type: "date",
        place: "user",
        name: "dob",
        label: "Your Birthday",
        min: 18,
        max: 50,
        helperText: "It's never too early to count down",
        errorText: "You need to enter your birthday",
      },
      {
        type: "select",
        place: "user",
        name: "gender",
        label: "Gender",
        options: genderOptions,
        placeholder: "Select your gender.",
        helperText: "Which gender best describes you?",
        errorText: "Please pick a gender to continue",
      },
      {
        type: "select",
        place: "prefrence",
        name: "interestedIn",
        label: "Looking for",
        options: interestedInOptions,
        placeholder: "Select a gender.",
        helperText: "Who would you like to meet?",
        errorText: "Please pick a gender to continue",
      },
      {
        type: "text",
        place: "user",
        name: "referralCode",
        label: "Referral code (optional)",
        placeholder: "friend_username",
        required: false,
        helperText: "Have a referral? Enter your friend's username.",
      },
    ],
  },
  {
    id: "preferences",
    required: true,
    title: "Set your match preferences.",
    fields: [
      {
        type: "range",
        place: "prefrence",
        name: "ageRange",
        label: "Preferred Age Range",
        min: 18,
        max: 50,
        step: 1,
        unit: "yrs",
        defaultValue: [18, 30],
        helperText: "Select the age range you are interested in.",
      },
      {
        type: "slider",
        place: "prefrence",
        name: "distance",
        label: "Preferred Distance",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 10,
        unit: "km",
        helperText: "Set the maximum distance for potential matches.",
      },
      {
        type: "select",
        place: "prefrence",
        name: "primary-goal",
        label: "What's Your Primary Goal?",
        options: goalOptions,
        placeholder: "My goal is...",
        helperText: "This helps us find better matches.",
        errorText: "Please select a goal to continue",
      },
    ],
  },
];

export const legacyOnboardingScreens: Screen[] = [
  {
    id: "intro",
    required: true,
    title: "Oh hey! Let's start with an intro.",
    fields: [
      {
        type: "text",
        place: "user",
        name: "nickname",
        label: "Nick name",
        placeholder: "Batman",
        helperText: "This will be your display name in the app.",
        errorText: "You need a nickname to use this app",
      },
      {
        type: "text",
        place: "user",
        name: "realName",
        label: "Real name",
        placeholder: "Bruce Wayne",
        helperText: "Shown only to your close friends.",
        errorText: "You need a name to use this app",
      },
      {
        type: "date",
        place: "user",
        name: "dob",
        label: "Your Birthday",
        min: 18,
        max: 50,
        helperText: "It's never too early to count down",
        errorText: "You need to enter your birthday",
      },
    ],
  },
  {
    id: "contact",
    required: true,
    title: "Let's keep your account secure.",
    fields: [
      {
        type: "number",
        place: "user",
        name: "phoneNumber",
        label: "Phone Number",
        placeholder: "+918080808080",
        helperText: "We'll never share your phone number.",
        errorText: "Please enter a valid phone number",
      },
      {
        type: "email",
        place: "user",
        name: "email",
        label: "Email Address",
        placeholder: "Enter your email",
        helperText: "Please provide a valid email address.",
        errorText: "Please enter a valid email address to continue",
      },
      {
        type: "text",
        place: "user",
        name: "referralCode",
        label: "Referral code (optional)",
        placeholder: "friend_username",
        required: false,
        helperText: "Have a referral? Enter your friend's username.",
      },
    ],
  },
  {
    id: "identity",
    required: true,
    title: "Let's personalize your matches",
    fields: [
      {
        type: "select",
        place: "user",
        name: "gender",
        label: "Gender",
        options: genderOptions,
        placeholder: "Select your gender.",
        helperText: "Which gender best describes you?",
        errorText: "Please pick a gender to continue",
      },
      {
        type: "select",
        place: "prefrence",
        name: "interestedIn",
        label: "Looking for",
        options: interestedInOptions,
        placeholder: "Select a gender.",
        helperText: "Who would you like to meet?",
        errorText: "Please pick a gender to continue",
      },
      {
        type: "multiselect",
        place: "user",
        name: "languages",
        label: "Languages",
        options: languageOptions,
        placeholder: "Select known languages",
        helperText:
          "You can select multiple languages you are comfortable with.",
        errorText: "Please pick at least one language to continue",
      },
    ],
  },
  {
    id: "tuning",
    required: true,
    title: "Let's tune your soulmate frequency",
    fields: [
      {
        type: "range",
        place: "prefrence",
        name: "ageRange",
        label: "Preferred Age Range",
        min: 18,
        max: 50,
        step: 1,
        unit: "yrs",
        defaultValue: [18, 30],
        helperText: "Select the age range you are interested in.",
      },
      {
        type: "slider",
        place: "prefrence",
        name: "distance",
        label: "Preferred Distance",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 10,
        unit: "km",
        helperText: "Set the maximum distance for potential matches.",
      },
    ],
  },
  {
    id: "intentions",
    required: true,
    title: "We'll find people who match your vibe.",
    fields: [
      {
        type: "select",
        place: "prefrence",
        name: "primary-goal",
        label: "What's Your Primary Goal?",
        options: goalOptions,
        placeholder: "My goal is...",
        helperText: "This helps us match you with like-minded people.",
        errorText: "Please select a goal to continue",
      },
      {
        type: "select",
        place: "prefrence",
        name: "secondary-goal",
        label: "What's your next priority?",
        options: goalOptions,
        placeholder: "My backup is...",
        helperText: "If not your primary goal, what else matters to you?",
        errorText: "Please select a goal to continue",
      },
      {
        type: "select",
        place: "prefrence",
        name: "tertiary-goal",
        label: "Any other goals or intentions?",
        options: goalOptions,
        placeholder: "My backup of backup is...",
        helperText: "What's another reason you're here?",
        errorText: "Please select a goal to continue",
      },
    ],
  },
];
